# Schema for the File (Field) Paths module.
# @TODO: Pathauto/Transliteration may need additional indenting.

field_config.third_party.filefield_paths:
  type: mapping
  label: 'FileField Path settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    filepath:
      type: string
      label: 'Path'
    pathauto_path:
      type: boolean
      label: 'Path clean with Pathauto'
    transliteration_path:
      type: boolean
      label: 'Transliterate path'
    filename:
      type: string
      label: 'Filename'
    pathauto_name:
      type: boolean
      label: 'Filename clean with Pathauto'
    transliteration_name:
      type: boolean
      label: 'Transliterate filename'
    retroactive_update:
      type: boolean
      label: 'Retroactive'
    active_updating:
      type: boolean
      label: 'Active'
